import type { Movie, MovieDetail, User, FeedItem } from '@/types';

export const MOCK_MOVIES: Movie[] = [
  {
    id: 238,
    title: 'The Godfather',
    poster_path: '/3bhkrj58Vtu7enYsLorgD1p0jCSx.jpg',
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    release_date: '1972-03-14',
    vote_average: 8.7,
    vote_count: 19500,
    genre_ids: [18, 80],
    overview: 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When patriarch Vito Corleone barely survives an attempt on his life, his youngest son, Michael, steps in to take care of the family business.',
  },
  {
    id: 278,
    title: 'The Shawshank Redemption',
    poster_path: '/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg',
    backdrop_path: '/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    release_date: '1994-09-23',
    vote_average: 8.7,
    vote_count: 24500,
    genre_ids: [18, 80],
    overview: 'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank State Penitentiary, where he puts his accounting skills to work for an amoral warden.',
  },
  {
    id: 240,
    title: 'The Godfather Part II',
    poster_path: '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
    backdrop_path: '/poec6RqOKY9iSiIUmfyfPfiLtvB.jpg',
    release_date: '1974-12-20',
    vote_average: 8.6,
    vote_count: 12500,
    genre_ids: [18, 80],
    overview: 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York, while his son Michael expands and tightens his grip on the crime syndicate.',
  },
  {
    id: 424,
    title: "Schindler's List",
    poster_path: '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
    backdrop_path: '/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg',
    release_date: '1993-12-15',
    vote_average: 8.6,
    vote_count: 14700,
    genre_ids: [18, 36, 10752],
    overview: 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory.',
  },
  {
    id: 155,
    title: 'The Dark Knight',
    poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop_path: '/hkBaDkMWbLaf8B1lsWsqX7an5cm.jpg',
    release_date: '2008-07-18',
    vote_average: 8.5,
    vote_count: 31200,
    genre_ids: [28, 80, 18],
    overview: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations.',
  },
  {
    id: 129,
    title: 'Spirited Away',
    poster_path: '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    backdrop_path: '/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg',
    release_date: '2001-07-20',
    vote_average: 8.5,
    vote_count: 14600,
    genre_ids: [16, 10751, 14],
    overview: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
  },
  {
    id: 496243,
    title: 'Parasite',
    poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    backdrop_path: '/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
    release_date: '2019-05-30',
    vote_average: 8.5,
    vote_count: 16700,
    genre_ids: [35, 53, 18],
    overview: "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
  },
  {
    id: 680,
    title: 'Pulp Fiction',
    poster_path: '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    backdrop_path: '/4cDFJr4HnXN5AdPw4AKrmLlMWdO.jpg',
    release_date: '1994-09-10',
    vote_average: 8.5,
    vote_count: 25700,
    genre_ids: [53, 80],
    overview: 'A burger-loving hit man, his philosophical partner, a drug-addled gangster\'s moll and a washed-up boxer converge in this sprawling, comedic crime caper.',
  },
  {
    id: 244786,
    title: 'Whiplash',
    poster_path: '/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
    backdrop_path: '/fRGxZuo7jJUWQsVg9PREb98Aclp.jpg',
    release_date: '2014-10-10',
    vote_average: 8.4,
    vote_count: 13700,
    genre_ids: [18, 10402],
    overview: 'Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.',
  },
  {
    id: 335984,
    title: 'Blade Runner 2049',
    poster_path: '/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
    backdrop_path: '/ilRyazdMJTN6UkFQJBMCsoTHXjE.jpg',
    release_date: '2017-10-03',
    vote_average: 7.9,
    vote_count: 13700,
    genre_ids: [878, 18],
    overview: "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos.",
  },
  {
    id: 438631,
    title: 'Dune: Part One',
    poster_path: '/d5NXSklpcvkD3hp33biqjk5M23b.jpg',
    backdrop_path: '/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg',
    release_date: '2021-09-15',
    vote_average: 7.8,
    vote_count: 15600,
    genre_ids: [878, 12],
    overview: 'Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family.',
  },
  {
    id: 872585,
    title: 'Oppenheimer',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg',
    release_date: '2023-07-19',
    vote_average: 8.1,
    vote_count: 18500,
    genre_ids: [18, 36],
    overview: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
  },
  {
    id: 667257,
    title: 'Tár',
    poster_path: '/aEjCsKkegWIz01YXNL4MkYhA7h9.jpg',
    backdrop_path: '/cZVMIjmUq2RzwYGrXc9jxFQ0YR5.jpg',
    release_date: '2022-10-07',
    vote_average: 7.2,
    vote_count: 4200,
    genre_ids: [18],
    overview: 'Set in the international world of classical music, the film centers on Lydia Tár, widely considered one of the greatest living composer-conductors.',
  },
  {
    id: 372058,
    title: 'Your Name.',
    poster_path: '/q719jXXEzOoYaps6babgKnONONX.jpg',
    backdrop_path: '/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg',
    release_date: '2016-08-26',
    vote_average: 8.5,
    vote_count: 10200,
    genre_ids: [10749, 16, 18],
    overview: 'Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?',
  },
  {
    id: 346648,
    title: 'Phantom Thread',
    poster_path: '/uSXxuqABs1eTLVpqWCRBFmNLNZ6.jpg',
    backdrop_path: '/mEcNwFXFMCzlnXKJXnrfTFJEiOq.jpg',
    release_date: '2017-12-25',
    vote_average: 7.5,
    vote_count: 6200,
    genre_ids: [18, 10749],
    overview: "Set in the glamour of 1950s post-war London, renowned dressmaker Reynolds Woodcock and his sister Cyril are at the center of the British fashion industry.",
  },
  {
    id: 769,
    title: 'GoodFellas',
    poster_path: '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
    backdrop_path: '/sw7mordbZxgITU877yTpZCud90M.jpg',
    release_date: '1990-09-19',
    vote_average: 8.5,
    vote_count: 13200,
    genre_ids: [18, 80],
    overview: 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.',
  },
  {
    id: 389,
    title: '12 Angry Men',
    poster_path: '/ppd84D2i9W8jXmsyInGyihiSyqz.jpg',
    backdrop_path: '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
    release_date: '1957-04-10',
    vote_average: 8.5,
    vote_count: 8200,
    genre_ids: [18],
    overview: 'The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young man is guilty or innocent of murdering his father.',
  },
  {
    id: 13,
    title: 'Forrest Gump',
    poster_path: '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    backdrop_path: '/7c9UVPPiTPltouxRVY6N9uugaVA.jpg',
    release_date: '1994-07-06',
    vote_average: 8.5,
    vote_count: 26300,
    genre_ids: [18, 10749],
    overview: 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined.',
  },
  {
    id: 637,
    title: 'Life Is Beautiful',
    poster_path: '/mfnkSeeNIxsKMwnLfNUf4Aahff1.jpg',
    backdrop_path: '/3hVDuHVQHJkCstpq9cQiIIkJFbL.jpg',
    release_date: '1997-12-20',
    vote_average: 8.5,
    vote_count: 12000,
    genre_ids: [10749, 18, 35],
    overview: "A touching story of an Italian Jewish man and how he tries to shield his son from the horrors of a World War II concentration camp.",
  },
  {
    id: 19404,
    title: 'Dilwale Dulhania Le Jayenge',
    poster_path: '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
    backdrop_path: '/90ez6ArvpO-dU2LAs5KvVHGwmXc.jpg',
    release_date: '1995-10-20',
    vote_average: 8.5,
    vote_count: 4300,
    genre_ids: [10749, 18],
    overview: 'Raj is a rich, careless young man. Simran is set to be married off to a man she has never met. When the two meet on a trip across Europe, romance blossoms.',
  },
];

export const MOCK_MOVIE_DETAIL: MovieDetail = {
  id: 238,
  title: 'The Godfather',
  poster_path: '/3bhkrj58Vtu7enYsLorgD1p0jCSx.jpg',
  backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
  release_date: '1972-03-14',
  vote_average: 8.7,
  vote_count: 19500,
  genres: [{ id: 18, name: 'Drama' }, { id: 80, name: 'Crime' }],
  overview: 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When patriarch Vito Corleone barely survives an attempt on his life, his youngest son, Michael, steps in to take care of the family business.',
  runtime: 175,
  tagline: 'An offer you can\'t refuse.',
  status: 'Released',
  credits: {
    cast: [
      { id: 3084, name: 'Marlon Brando', character: 'Vito Corleone', profile_path: '/fuTEPMsBtV1zE98ujPONbKiYDc2.jpg' },
      { id: 1158, name: 'Al Pacino', character: 'Michael Corleone', profile_path: '/2RNjFPHVRotDzvOoClnEtdpVqe5.jpg' },
      { id: 3085, name: 'James Caan', character: 'Sonny Corleone', profile_path: '/uWBnDjMFH6I3VjBKqPCKAKjxSLv.jpg' },
      { id: 4140, name: 'Diane Keaton', character: 'Kay Adams', profile_path: '/84kIBoUhJNNRGJWkqsHuEUHtg8v.jpg' },
      { id: 3087, name: 'Robert Duvall', character: 'Tom Hagen', profile_path: '/tnC6eMUeMV9BjWBP3rHGBGRETek.jpg' },
    ],
    crew: [
      { id: 1776, name: 'Francis Ford Coppola', job: 'Director', department: 'Directing' },
      { id: 10909, name: 'Gordon Willis', job: 'Director of Photography', department: 'Camera' },
      { id: 1777, name: 'Nino Rota', job: 'Original Music Composer', department: 'Sound' },
    ],
  },
};

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    username: 'cinematica',
    displayName: 'Cinematica',
    email: 'cinematica@example.com',
    bio: 'Film nerd. Loves noir and 70s cinema.',
    avatar: null,
    createdAt: '2024-01-15',
    moviesWatched: 342,
  },
  {
    id: 'u2',
    username: 'director_of_dreams',
    displayName: 'Dream Director',
    email: 'dreams@example.com',
    bio: 'Aspiring filmmaker. Kubrick devotee.',
    avatar: null,
    createdAt: '2024-02-20',
    moviesWatched: 215,
  },
  {
    id: 'u3',
    username: 'velvet_reel',
    displayName: 'Velvet Reel',
    email: 'velvet@example.com',
    bio: 'European art house and slow cinema.',
    avatar: null,
    createdAt: '2024-03-10',
    moviesWatched: 489,
  },
  {
    id: 'u4',
    username: 'neon_frames',
    displayName: 'Neon Frames',
    email: 'neon@example.com',
    bio: 'Sci-fi, dystopian, and Hong Kong cinema.',
    avatar: null,
    createdAt: '2024-03-25',
    moviesWatched: 178,
  },
  {
    id: 'u5',
    username: 'golden_ratio',
    displayName: 'Golden Ratio',
    email: 'golden@example.com',
    bio: 'Cinematography and visual storytelling.',
    avatar: null,
    createdAt: '2024-04-05',
    moviesWatched: 267,
  },
];

export const MOCK_FEED_ITEMS: FeedItem[] = [
  {
    id: 'fi1',
    type: 'review',
    userId: 'u1',
    username: 'cinematica',
    displayName: 'Cinematica',
    userAvatar: null,
    movieId: 238,
    movieTitle: 'The Godfather',
    moviePoster: '/3bhkrj58Vtu7enYsLorgD1p0jCSx.jpg',
    movieYear: '1972',
    rating: 5,
    reviewText: "An absolute masterpiece. Coppola's direction is immaculate and Brando's performance is transcendent. The way this film understands power, family, and loyalty is unmatched.",
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'fi2',
    type: 'log',
    userId: 'u3',
    username: 'velvet_reel',
    displayName: 'Velvet Reel',
    userAvatar: null,
    movieId: 667257,
    movieTitle: 'Tár',
    moviePoster: '/aEjCsKkegWIz01YXNL4MkYhA7h9.jpg',
    movieYear: '2022',
    rating: 4.5,
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
  {
    id: 'fi3',
    type: 'review',
    userId: 'u4',
    username: 'neon_frames',
    displayName: 'Neon Frames',
    userAvatar: null,
    movieId: 335984,
    movieTitle: 'Blade Runner 2049',
    moviePoster: '/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
    movieYear: '2017',
    rating: 5,
    reviewText: "Villeneuve has crafted something extraordinary. Roger Deakins' cinematography is otherworldly — every frame feels like a painting. A worthy successor.",
    createdAt: new Date(Date.now() - 8 * 3600000).toISOString(),
  },
  {
    id: 'fi4',
    type: 'log',
    userId: 'u2',
    username: 'director_of_dreams',
    displayName: 'Dream Director',
    userAvatar: null,
    movieId: 244786,
    movieTitle: 'Whiplash',
    moviePoster: '/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
    movieYear: '2014',
    rating: 4.5,
    createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
  },
  {
    id: 'fi5',
    type: 'review',
    userId: 'u5',
    username: 'golden_ratio',
    displayName: 'Golden Ratio',
    userAvatar: null,
    movieId: 872585,
    movieTitle: 'Oppenheimer',
    moviePoster: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    movieYear: '2023',
    rating: 4,
    reviewText: "Nolan's most ambitious work. The non-linear structure is hypnotic and Cillian Murphy's performance is career-best. The Trinity test sequence is breathtaking.",
    createdAt: new Date(Date.now() - 18 * 3600000).toISOString(),
  },
  {
    id: 'fi6',
    type: 'log',
    userId: 'u1',
    username: 'cinematica',
    displayName: 'Cinematica',
    userAvatar: null,
    movieId: 496243,
    movieTitle: 'Parasite',
    moviePoster: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    movieYear: '2019',
    rating: 5,
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
];

export const GENRE_MAP: Record<number, string> = {
  28: 'Action',
  12: 'Adventure',
  16: 'Animation',
  35: 'Comedy',
  80: 'Crime',
  99: 'Documentary',
  18: 'Drama',
  10751: 'Family',
  14: 'Fantasy',
  36: 'History',
  27: 'Horror',
  10402: 'Music',
  9648: 'Mystery',
  10749: 'Romance',
  878: 'Sci-Fi',
  10770: 'TV Movie',
  53: 'Thriller',
  10752: 'War',
  37: 'Western',
};

export const CURATED_COLLECTIONS = [
  {
    id: 'modern-noir',
    title: 'Modern Noir Essentials',
    description: 'Contemporary crime cinema that channels the shadows of classic noir.',
    movieIds: [680, 769, 238, 496243, 244786],
  },
  {
    id: 'sci-fi-visions',
    title: 'Visions of Tomorrow',
    description: 'Science fiction that challenges perception and expands imagination.',
    movieIds: [335984, 438631, 129, 872585],
  },
  {
    id: 'emotional-journeys',
    title: 'Emotional Journeys',
    description: 'Films that leave a permanent mark on the soul.',
    movieIds: [278, 424, 637, 13, 19404],
  },
];
